meta:
  name: After test suite
configuration:
  scheme: http
  host: 127.0.0.1
  port: 3027
specs:
  - name: after test hook inline sync funtion
    after_test:
      run_type: inline
      inline:
        function: !!js/function >
          function() {
              var keys = Object.keys(this);
              if (keys.length !== 5)
                  throw new Error("after test context doesn't have expected keys");

              var body = JSON.parse(this.response.body);
              if (body.param1 !== 'value2')
                 throw new Error('unexpected response');
          }
    request: &default_request
      path: /echoQueryParams
      method: get
      query_params:
        - name: param1
          value: value2
    response: &default_response
      json_data:
        - path: $
          value:
            param1: value2

  - name: after test hook inline async funtion
    after_test:
      run_type: inline
      inline:
        function: !js/asyncFunction >
          function() {
              var body = JSON.parse(this.response.body);
              if (body.param1 !== 'value2')
                 throw new Error('unexpected response');
          }
    request: *default_request
    response: *default_response

  - name: after test hook module sync funtion
    after_test:
      run_type: module
      module:
        module_path: modules/after_test.js
        function_name: afterTestSyncSuccess
    request: *default_request
    response: *default_response

  - name: after test hook module async funtion
    after_test:
      run_type: module
      module:
        module_path: modules/after_test.js
        function_name: afterTestAsyncSuccess
    request: *default_request
    response: *default_response

  - name: after test hook inline sync funtion throws error - should fail
    after_test:
      run_type: inline
      inline:
        function: !!js/function >
          function() {
              var body = JSON.parse(this.response.body);
              if (body.param1 !== 'value2')
                 throw new Error('unexpected response');
            throw new Error('error thrown in after test hook');
          }
    request: *default_request
    response: *default_response

  - name: after test hook inline async funtion throws error - should fail
    after_test:
      run_type: inline
      inline:
        function: !js/asyncFunction >
          function() {
              var body = JSON.parse(this.response.body);
              if (body.param1 !== 'value2')
                 throw new Error('unexpected response');
            throw new Error('error thrown in after test hook');
          }
    request: *default_request
    response: *default_response

  - name: after test hook module sync funtion throws error - should fail
    after_test:
      run_type: module
      module:
        module_path: modules/after_test.js
        function_name: afterTestSyncError
    request: *default_request
    response: *default_response

  - name: after test hook module async funtion throws error - should fail
    after_test:
      run_type: module
      module:
        module_path: modules/after_test.js
        function_name: afterTestAsyncError
    request: *default_request
    response: *default_response

  - name: after test hook module async funtion rejected promise - should fail
    after_test:
      run_type: module
      module:
        module_path: modules/after_test.js
        function_name: afterTestAsyncRejectedPromise
    request: *default_request
    response: *default_response